### ISSUE TITLE
what is unit of the energy function ?

### ISSUE THREAD

**Issue by wangleiphy** [wangleiphy/jax-flow-matching#7]
Suppose I am going to compute the Boltzmann factor: 
exp( -e/ (k_B*T) )
where `T = data['T']` is the temperature in Kelvin loaded from the data file. 

How should I compute the dimensionless number e/ (k_B*T) in the code ?

**Comment by WangXinyan940** [comment]
The unit of the energy function is kJ/mol. I guess exp(- E / 8.314e-3 / T) is okay, where the unit of E and T are kJ/mol and Kelvin.
